---
- name: Deploy servers
  hosts: localhost
  gather_facts: no

  vars_files:
    - environments/{{ env }}/group_vars/rax.yml

  tasks:
    - name: Ensure servers
      rax:
        wait: yes
        wait_timeout: 600

        name: "{{ env }}-"
        group: "{{ env }}"
        auto_increment: yes
        count: "{{ server.count|default(1) }}"
        exact_count: yes

        image: "{{ server.image }}"
        flavor: "{{ server.flavor }}"
        region: "{{ server.region|default('IAD') }}"

        key_name: "{{ server.key }}"
      register: servers

    - name: Register new hosts
      add_host:
        hostname: "{{ item.name }}"
        ansible_host: "{{ item.rax_accessipv4 }}"
        groups: "{{ env }}"
      with_items: servers.success
      when: servers|changed

- name: Trust hosts
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Fetch host keys
      command: ssh-keyscan {{ hostvars[item].rax_accessipv4 }}
      register: host_ssh_keys
      with_items: groups[env]
      changed_when: false

    - name: Add host keys
      lineinfile:
        dest: ~/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ item.1 }}"
      with_subelements:
        - host_ssh_keys.results
        - stdout_lines

- name: Bootstrap hosts
  hosts: "{{ env }}"
  gather_facts: no

  vars_files:
    - environments/{{ env }}/group_vars/rax.yml

  roles:
    - sigma.coreos-bootstrap

  tasks:
    - name: Install pip
      command: ~/bin/python -m ensurepip
      args:
        creates: ~/pypy/site-packages/pip

    - name: Install docker-py
      pip:
        name: docker-py
        state: latest

- name: Configure access
  hosts: "{{ env }}"
  gather_facts: yes

  tasks:
    - name: Ensure SSH keys
      authorized_key:
        user: "{{ ansible_ssh_user }}"
        key: https://github.com/{{ item }}.keys
      with_items:
        - dirn
        - jonafato

- name: Start services
  hosts: "{{ env }}"
  gather_facts: no

  tasks:
    - name: Ensure units directory
      file:
        path: ~/units
        state: directory
        owner: core
        group: core

    - name: Start services
      become: yes
      service:
        name: "{{ item }}.service"
        state: started
      with_items:
        - etcd
        - fleet

- name: Nginx
  hosts: "{{ env }}"
  gather_facts: no

  vars_files:
    - environments/{{ env }}/group_vars/services.yml

  tasks:
    - name: Upload Nginx service unit
      template:
        src: templates/nginx@.service.j2
        dest: ~/units/nginx@.service
      register: unit

    - block:
        - name: Stop Nginx
          command: fleetctl stop ~/units/nginx@{{ item }}.service
          ignore_errors: yes
          with_sequence: count="{{ nginx.count|default(1) }}"

        - name: Remove Nginx units
          command: fleetctl destroy ~/units/nginx@{{ item }}.service
          ignore_errors: yes
          with_sequence: count="{{ nginx.count|default(1) }}"

        - name: Register Nginx units
          command: fleetctl submit ~/units/nginx@{{ item }}.service
          with_sequence: count="{{ nginx.count|default(1) }}"

        - name: Start Nginx
          command: fleetctl start ~/units/nginx@{{ item }}.service
          with_sequence: count="{{ nginx.count|default(1) }}"
      when: unit|changed

- name: Postgres
  hosts: "{{ env }}"
  gather_facts: no

  vars_files:
    - environments/{{ env }}/group_vars/services.yml

  tasks:
    - name: Upload Postgres service unit
      template:
        src: templates/postgres@.service.j2
        dest: ~/units/postgres@.service
      register: unit

    - block:
        - command: fleetctl stop ~/units/postgres@{{ item }}.service
          ignore_errors: yes
          with_sequence: count="{{ postgres.count|default(1) }}"

        - command: fleetctl destroy ~/units/postgres@{{ item }}.service
          ignore_errors: yes
          with_sequence: count="{{ postgres.count|default(1) }}"

        - command: fleetctl submit ~/units/postgres@{{ item }}.service
          with_sequence: count="{{ postgres.count|default(1) }}"

        - command: fleetctl start ~/units/postgres@{{ item }}.service
          with_sequence: count="{{ postgres.count|default(1) }}"
      when: unit|changed
